import type { Metadata } from "next";
// import { Pixel Font7 } from "next/font";
import "./globals.scss";
import Header from "@/components/header/Header";

// const inter = Arial({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body >
                <div className="wrapper">
                    <Header/>
                    <main>
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
