import type { Metadata } from "next";

import "./globals.scss";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import RightSidebar from "@/components/right-sideber/RightSidebar";
import LeftSidebar from "@/components/left-sidebar/LeftSidebar";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru" >
            <body >
                <div className="wrapper">
                    <Header/>
                    <main className="main  _container">
                        <LeftSidebar/>
                        <div className="main-content">
                            {children}
                        </div>
                        <RightSidebar/>
                    </main>
                    <Footer/>
                </div>
            </body>
        </html>
    );
}
